name: 'express-actions'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    start-app:
        runs-on: ubuntu-latest
        steps:
          - name: Check out Repository Code
            uses: actions/checkout@v4
          
          - name: Setup server
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

          - name: Install Dependencies
            run: npm ci

          - name: Start up server
            run: npm start
