name: 'express-actions'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    start-app:
        runs-on: ubuntu-latest
        steps:
          - name: Check out Repository Code
            uses: actions/checkout@v4
          
          - name: Setup server
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

          - name: Install PNPM
            run: npm install -g pnpm

          - run: pnpm install

          - name: Start up server
            run: ls

          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
              api-key: ${{ secrets.MY_RENDER_API_KEY }}
